source "${LIB}/completion/base.sh"

source "${LIB}/completion/android.sh"
source "${LIB}/completion/bower.sh"
source "${LIB}/completion/bundle.sh"
source "${LIB}/completion/capistrano.sh"
source "${LIB}/completion/docker-compose.sh"
source "${LIB}/completion/docker.sh"
source "${LIB}/completion/gem.sh"
source "${LIB}/completion/grunt.sh"
source "${LIB}/completion/maven.sh"
source "${LIB}/completion/nim.sh"
source "${LIB}/completion/npm.sh"
source "${LIB}/completion/pip.sh"
source "${LIB}/completion/rake.sh"
source "${LIB}/completion/ruby.sh"
source "${LIB}/completion/vagrant.sh"
source "${LIB}/completion/yeoman-generators.sh"
